### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Viswas-Programs** [North-West-Wind/opensurviv-client#1]
This index.html, didn't work. 
If you look at the console, the error states that it can't connect to the local host.
this is the screen :-
![image](https://user-images.githubusercontent.com/115633223/202230642-f7afce88-0adf-401c-87ec-407c0be34024.png)

**Comment by North-West-Wind** [comment]
That's because this is still very early stage and it doesn't actually connect to a real surviv server :/
This project is meant to work with [opensurviv-server](https://github.com/North-West-Wind/opensurviv-server)

**Comment by Viswas-Programs** [comment]
Oh, so I need to download opensurviv-server?
If needed, I'll download because surviv.io is officially dead, like the great game is now dead because kong decided to.
I just thought we, as the dev community, can do anything.

**Comment by North-West-Wind** [comment]
I try to be active on this project, but I have a lot of other things to take care of. I will definitely keep working on it though.

Also, opensurviv-server will need to be self-hosted.

> I just thought we, as the dev community, can do anything.

Of course we can. All we need is time.

**Comment by Viswas-Programs** [comment]
> Also, opensurviv-server will need to be self-hosted.
Does that mean I need to host my own server with node.js? 
bruh, I don't have node.js, so I can't host my own server right?
Or, is it only requiring download?

**Comment by North-West-Wind** [comment]
Installing node.js is not that hard. The server folder can be placed anywhere. You will need to know its path though.

Then, launch a terminal and `cd` to that path. Run `npm install` followed by `npm test` and it should be up and running.

**Comment by Viswas-Programs** [comment]
Oh ok. will try, thanks for the tutorial, since I dont know any thing about node.js

**Comment by Viswas-Programs** [comment]
Now, it works, but it's basic, y'know, so, can I help out with this project for ideas?
and, this game, at this stage, is indicating that you worked hard for this :)

**Comment by North-West-Wind** [comment]
If you can contribute to the code, that will be the best. I accept ideas, but please don't expect them to come in the near future.

Another way you can help is by sharing this project to people who may be helpful.

**Comment by Viswas-Programs** [comment]
bro I made a new object! a bush!
I will create  a PR about that, merge it bro, test it for yourself, it works for me, just like a bush.!

**Comment by Viswas-Programs** [comment]
Hello there again, I tested your new update, and now the fists don't show up!
Please fix that. 
thanking you,
Viswas.

**Comment by North-West-Wind** [comment]
Yes because it's going through some huge changes. It should hopefully be fixed soon when I push the new code.

**Comment by Viswas-Programs** [comment]
Oh, good luck :)
I will check tomorrow then... (according to IST)
And also, one new idea, is implementing buildings. I have found the assets of surviv.io in an old kongregate forum post. they have the drive link open still now!
link:- https://drive.google.com/open?id=1qhaDdNCsisBu_7gvMNmyn_zkG4kyAZix

**Comment by North-West-Wind** [comment]
Yup it's now using typescript. Also thanks for the asset link

**Comment by Viswas-Programs** [comment]
Hello bro, can you tell me where is the map data stored, like the map itself, and the image of it?
coz, I like to create a river and a beach on the map instead of just thick black borders.

**Comment by North-West-Wind** [comment]
The map is yet to be implemented. Everything right now is randomly generated on a fixed size empty map.
