### ISSUE TITLE
Too hard to edit files

### ISSUE THREAD

**Issue by Viswas-Programs** [North-West-Wind/opensurviv-client#4]
I wanted to add another object. The Barrel. 
While I did 95% of the work, The real problem arises with bundle.min.js. It's so hard to edit that I literally broke it. 
So, How to edit the Bundle.min.js file bro, is there any "uncompiling" process?

**Comment by North-West-Wind** [comment]
You only need to edit the typescript files. `bundle.min.js` is compiled from those typescript files. After editing the typescript files, run `npm run build` to compile them.

**Comment by Viswas-Programs** [comment]
ok, so what folder do i need to do run build?
in the fork itself (opensurviv-client) or inside it? (opensurviv-client/types)?

**Comment by North-West-Wind** [comment]
`npm run build` will automatically build the files in `src` into `scripts/bundle.min.js`

**Comment by Viswas-Programs** [comment]
Ok, but what folder should I cd to, to execute the command? 
like I need to do build in src or toplevel?

**Comment by North-West-Wind** [comment]
Just the main directory

**Comment by Viswas-Programs** [comment]
One more thing, the damage part doesn't work tho.
If i hit a bush 5 times with my fist, it should break innit?
But it doesn't, neither for the tree.

**Comment by Viswas-Programs** [comment]
Ok, I followed your steps, but it doesn't seem to be working. 
Now, I wanted to add a barrel, so I did the respective things, but all of a sudden, the player doesn't move. 
It's not because of your update though, it worked for me, but after adding the barrel files and changing index.ts to export barrel along with others, now the player doesn't move and the barrel doesn't show up.

**Comment by Viswas-Programs** [comment]
Hello bro, is there any methods for the player to die or take damage?
Because, with barrels, if exploded, the player should take damage right? but from barrel.ts, importing the player from entities doesn't have that method.

**Comment by North-West-Wind** [comment]
There's a way to take damage, but dying is not implemented yet. There is a `tick` method for all objects and entities which has the array of entities and objects passed into it. So one possible way to check if the player is caught in the explosion is to expand the barrel's hitbox and check if there's any collision with it.

**Comment by Viswas-Programs** [comment]
Can you say  the way to take damage though?
I mean, if you take 100 damage (or 1 in your code), the player dies right?
So, can you tell me that way of taking damage.

**Comment by North-West-Wind** [comment]
Just call `entity.damage(amount)`

**Comment by Viswas-Programs** [comment]
wait, let me explain what I am doing
Like crate, I over-ride the die method, of entities, to die, and the player should die
`die(){
this.die;
Player.damage(100)`
in the top, there is `import { Player } from "../entities`
but in VS Code, it doesn't come up
Let me send you  a photo

**Comment by North-West-Wind** [comment]
The `Player` you imported is the class, not the actual entity. The `die()` method of the barrel is used for the dying barrel, not player.

To actually get the player entity, you need to use the `tick` method of the barrel class.

**Comment by Viswas-Programs** [comment]
OHH, I get it. so what should I give to the tick method of the barrel though?

**Comment by North-West-Wind** [comment]
Since barrel extends the `GameObject` class, you can hold Ctrl and click on `GameObject` to see how it's defined.

**Comment by Viswas-Programs** [comment]
no not that, what should I give as parameters to the tick method?

**Comment by North-West-Wind** [comment]
The `tick` method of the `Barrel` class should accept the same parameters as the `tick` method defined in the `GameObject` class.

As you iterate through the entities, check if the entity `type` (a property of the `Entity` class) is "player". If it is, and it is colliding with the explosion, call `entity.damage(amount)`. There is no need to call `entity.die()` since in the next tick the entity will check if its health < 0 and call `die()` by itself.

**Comment by Viswas-Programs** [comment]
Yeah, but where are the entities stored, to even loop through them?
And, even If I hardcode them, It still says entity.damage property doesn't exist (in vs code)

**Comment by North-West-Wind** [comment]
This is where objects' `tick` method get called:  
https://github.com/North-West-Wind/opensurviv-server/blob/main/src/index.ts#L134

This is the objects' `tick` method:  
https://github.com/North-West-Wind/opensurviv-server/blob/main/src/types/objects.ts#L135-L137

So you should make a `tick` method in `Barrel` class, and do something like the following:
```js
tick(entities: Entity[], objects: GameObject[]) {
  // Iterate through entities
  for (const entity of entities) {
    // Check for collision and type
    if (entity.collided(this.hitbox, this.position, this.direction) && entity.type === "player") {
      // Damage the entity
      entity.damage(100);
    }
  }
}
```

**Comment by Viswas-Programs** [comment]
ok bro thanks for the code
I am saying again, I only noob in JS

**Comment by North-West-Wind** [comment]
I mentioned the `tick` method is called here:  
https://github.com/North-West-Wind/opensurviv-server/blob/main/src/index.ts#L134

As for if the entity list is hardcoded, I would say it is dynamic.
It is defined here:
https://github.com/North-West-Wind/opensurviv-server/blob/main/src/index.ts#L18

Once a player connects, it gets pushed into the entity list:
https://github.com/North-West-Wind/opensurviv-server/blob/main/src/index.ts#L61

And finally the entity list gets passed to the `tick` method of each object at:
https://github.com/North-West-Wind/opensurviv-server/blob/main/src/index.ts#L134 (the first link)

> Now, this tick method is ok, but I still am not sure what argument to give to this tick method.
So, you will not need to worry about this part. It is already handled.

**Comment by Viswas-Programs** [comment]
oh thanks for the explanation bro.
